version: 0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  BuildEnvironment: appveyor

cache:
  - packages # preserve "packages" directory in the root of build folder

build_script: assets\build.bat pack

artifacts:
  - path: 'build\**\*.nupkg'

test: off  

deploy:
  provider: NuGet
  api_key:
    secure: yNaPU9GGsdDdMjOB5tbQTuIIq4DFHNGUkZP1ZTDDCKQG3g7pZjxcBFZblTMeIawA
  artifact: /.*build.*\.nupkg/
  on:
    branch: master
