version: 0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: src/FlatFile.sln

after_test:
  - ps: .\assets\pack.ps1

artifacts: 
  # pushing all *.nupkg files in directory
  - path: '**\*.nupkg' # find all NuGet packages recursively

deploy:
  provider: NuGet
  api_key:
    secure: yNaPU9GGsdDdMjOB5tbQTuIIq4DFHNGUkZP1ZTDDCKQG3g7pZjxcBFZblTMeIawA
